### ISSUE TITLE
Can not support json Object type

### ISSUE THREAD

**Issue by pj15317** [Risto-Stevcev/json-to-dot#1]
echo "{\"foo\":[\"bar\",\"baz\"],\"obj\":{\"a\":1},\"baz\":[\"norf\"]}" | json-to-dot

error:

/usr/local/lib/node_modules/json-to-dot/index.js:6
    return dependencies.reduce((acc, dependency) => acc + `  "${node}" -> "${dependency}"\n`, acc)
                        ^

TypeError: dependencies.reduce is not a function
    at Object.entries.reduce (/usr/local/lib/node_modules/json-to-dot/index.js:6:25)
    at Array.reduce (<anonymous>)
    at jsonToDot (/usr/local/lib/node_modules/json-to-dot/index.js:5:24)
    at Socket.process.stdin.on (/usr/local/lib/node_modules/json-to-dot/index.js:14:45)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Risto-Stevcev** [comment]
Thanks for the input. What's the use case for it and how would I go about supporting that?

It needs to translate the json into a dot graph which is why I didn't support arbitrary json, just json in the form of {key: String[]}, where all values in the array refer to an existing key in the object

**Comment by Risto-Stevcev** [comment]
Closing this for now, I'll reopen if needed
